### ISSUE TITLE
Error On Synology NAS

### ISSUE THREAD

**Issue by StuBFrost** [p10tyr/rtsp-to-onvif#14]
Hello.  I am trying to use your docker image on my Synology NAS.  I have 5 cameras that I want to "present" to Protect but I am getting errors when the container starts as follows:

10:59:28.474 ERROR NET_SCAN: No interface with MAC 1a:11:b0:19:3f:b3
10:59:28.474 INFO  NET_CONF: ADD - rtsp2onvif_0 MAC: 1A:11:B0:19:3F:B3
10:59:28.535 DEBUG Command failed: ip link add rtsp2onvif_0 link eth0 address 1A:11:B0:19:3F:B3 type macvlan mode bridge
RTNETLINK answers: Resource busy
10:59:28.535 INFO  NET_CONF: DHCP - rtsp2onvif_0
10:59:28.733 DEBUG Command failed: dhclient rtsp2onvif_0
Cannot find device "rtsp2onvif_0"
10:59:28.734 ERROR NET_SCAN: No interface with MAC 1a:11:b0:73:7f:d5
10:59:28.734 INFO  NET_CONF: ADD - rtsp2onvif_1 MAC: 1A:11:B0:73:7F:D5
10:59:28.736 DEBUG Command failed: ip link add rtsp2onvif_1 link eth0 address 1A:11:B0:73:7F:D5 type macvlan mode bridge
RTNETLINK answers: Resource busy
10:59:28.736 INFO  NET_CONF: DHCP - rtsp2onvif_1
10:59:28.748 DEBUG Command failed: dhclient rtsp2onvif_1
Cannot find device "rtsp2onvif_1"
10:59:28.749 ERROR NET_SCAN: No interface with MAC 1a:11:b0:1b:7d:59
10:59:28.749 INFO  NET_CONF: ADD - rtsp2onvif_2 MAC: 1A:11:B0:1B:7D:59
10:59:28.750 DEBUG Command failed: ip link add rtsp2onvif_2 link eth0 address 1A:11:B0:1B:7D:59 type macvlan mode bridge
RTNETLINK answers: Resource busy
10:59:28.750 INFO  NET_CONF: DHCP - rtsp2onvif_2
10:59:28.763 DEBUG Command failed: dhclient rtsp2onvif_2
Cannot find device "rtsp2onvif_2"
10:59:28.763 ERROR NET_SCAN: No interface with MAC 1a:11:b0:ff:fd:b1
10:59:28.763 INFO  NET_CONF: ADD - rtsp2onvif_3 MAC: 1A:11:B0:FF:FD:B1
10:59:28.765 DEBUG Command failed: ip link add rtsp2onvif_3 link eth0 address 1A:11:B0:FF:FD:B1 type macvlan mode bridge
RTNETLINK answers: Resource busy
10:59:28.765 INFO  NET_CONF: DHCP - rtsp2onvif_3
10:59:28.776 DEBUG Command failed: dhclient rtsp2onvif_3
Cannot find device "rtsp2onvif_3"
10:59:28.776 ERROR NET_SCAN: No interface with MAC 1a:11:b0:9b:5b:db
10:59:28.776 INFO  NET_CONF: ADD - rtsp2onvif_4 MAC: 1A:11:B0:9B:5B:DB
10:59:28.779 DEBUG Command failed: ip link add rtsp2onvif_4 link eth0 address 1A:11:B0:9B:5B:DB type macvlan mode bridge
RTNETLINK answers: Resource busy
10:59:28.779 INFO  NET_CONF: DHCP - rtsp2onvif_4
10:59:28.790 DEBUG Command failed: dhclient rtsp2onvif_4
Cannot find device "rtsp2onvif_4"
10:59:28.791 ERROR NET_SCAN: No interface with MAC 1a:11:b0:19:3f:b3
10:59:28.791 ERROR Failed to find IP address for MAC address 1A:11:B0:19:3F:B3
(node:1) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.

Any idea why the ip link add command fails?

Thanks

**Comment by StuBFrost** [comment]
Found the issue.  Should be ovs_eth0 rather than eth0.

**Comment by yngndrw** [comment]
Just to add to this, if you're using the Synology link aggregation functionality (Aka bonding), the ethernet interface would be called `bond0`.
