### ISSUE TITLE
Cannot find device "enp2s0"

### ISSUE THREAD

**Issue by balgerion** [p10tyr/rtsp-to-onvif#6]
It looks like network card name problem , is there anyway to change that ?

![{E7342F68-EC78-4641-88B8-CE7D3A81C7D1}](https://github.com/user-attachments/assets/2df41348-2443-41fb-8047-85f03a37a234)

docker srv network cards:
![{E6713D5C-3B0D-4502-A517-8BF79B7EB9CD}](https://github.com/user-attachments/assets/32938d7e-f9e7-4541-ad17-134ff0ff7049)

**Comment by yngndrw** [comment]
It looks like `ens18` is the network interface which you need to use. You can set it in the config yaml file:
https://github.com/p10tyr/rtsp-to-onvif/blob/release/config.example.yaml#L3

**Comment by balgerion** [comment]
F*** SRY!! :) i rly need caffe, everything is working. thank you!

**Comment by balgerion** [comment]
Can i ask for little help with m,ulti camera setup ? :) for one camera is working without any issue , but when i try to add one more it looks like that:
![{1D141AD4-159D-448E-9071-1457E98E0A81}](https://github.com/user-attachments/assets/dea982bb-b7dc-4084-b35d-0952fd152063)


my config file
onvif:
  - name: FapLab_cam1
    dev: ens18
    target:
      hostname: 192.168.1.104
      ports:
        rtsp: 554
        snapshot: 80
    highQuality:
      rtsp: /h264
      snapshot: /
      width: 1920
      height: 1080
      framerate: 30
      bitrate: 4096
      quality: 4
    ports:
      server: 8081
      rtsp: 8554
      snapshot: 9090
    uuid: c9d11626-e3ab-4cb8-8875-da2272443a6f
    mac: 1A:11:B0:3B:D5:9F
  - name: FapLab_cam0
    dev: ens18
    target:
      hostname: 192.168.1.69
      ports:
        rtsp: 554
        snapshot: 80
    highQuality:
      rtsp: /
      snapshot: /
      width: 1920
      height: 1080
      framerate: 30
      bitrate: 2048
      quality: 4
    ports:
      server: 9081
      rtsp: 9554
      snapshot: 9091
    uuid: 20a52438-4a3c-49dc-86a5-c3b4ecaa490d
    mac: 1A:11:B0:FD:B7:95

**Comment by p10tyr** [comment]
That s good to hear its sorted now. I am thinking of making some webGUI to make this even easier to setup and then even monitor.

I will see if i can further improve the error messages though!

**Comment by p10tyr** [comment]
I have created another repo that uses a GUI framework. My goal is to have that GUI configure everything for you based on the interfaces it found on your machine its running on. I will bolt it on as a docker-compose thing at some point.

https://github.com/[p10tyr/rtsp-to-onvif-nicegui](https://github.com/p10tyr/rtsp-to-onvif-nicegui)

Hope everything been ok since? 😄

**Comment by balgerion** [comment]
Cześć Piotr , 

Im running 6 cameras on your onvif proxy and it’s rly awesome. Once every few days server is hanging out but I have automatic container restart based on logs so it’s not a big issue for me. 

Logs if you want ;)
![IMG_3436](https://github.com/user-attachments/assets/aec5f6d2-e257-406f-ac93-ca236d0001b4)
